/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JLabel;

/**
 *
 * @author Alici
 */
public class PanelProductoSeleccionado extends javax.swing.JPanel {

    public void setNombre(String nombre) {
        labelNombre.setText(nombre);
    }

    public void setCantidad(String cantidad) {
        labelCantidad.setText(cantidad);
    }

    public void setSubtotal(String subtotal) {
        labelSubtotal.setText(subtotal);
    }

    /**
     * Creates new form PanelProductoSeleccionado
     */
    public PanelProductoSeleccionado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                labelNombre = new javax.swing.JLabel();
                lableSubtotalTitulo = new javax.swing.JLabel();
                labelCantidadTitulo = new javax.swing.JLabel();
                labelSubtotal = new javax.swing.JLabel();
                labelCantidad = new javax.swing.JLabel();
                panelBorde = new javax.swing.JPanel();

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));

                setBackground(new java.awt.Color(245, 245, 245));
                setMaximumSize(new java.awt.Dimension(476, 150));
                setMinimumSize(new java.awt.Dimension(476, 150));
                setPreferredSize(new java.awt.Dimension(476, 150));
                setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                labelNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                labelNombre.setText("Nombre");
                add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 409, -1));

                lableSubtotalTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                lableSubtotalTitulo.setText("Subtotal");
                add(lableSubtotalTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

                labelCantidadTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                labelCantidadTitulo.setText("Cantidad");
                add(labelCantidadTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, -1));

                labelSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                labelSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                labelSubtotal.setText("$ 0.00");
                add(labelSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 190, 60));

                labelCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                labelCantidad.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
                labelCantidad.setText("0");
                add(labelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 190, 70));

                panelBorde.setBackground(new java.awt.Color(217, 217, 217));

                javax.swing.GroupLayout panelBordeLayout = new javax.swing.GroupLayout(panelBorde);
                panelBorde.setLayout(panelBordeLayout);
                panelBordeLayout.setHorizontalGroup(
                                panelBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 480, Short.MAX_VALUE));
                panelBordeLayout.setVerticalGroup(
                                panelBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 10, Short.MAX_VALUE));

                add(panelBorde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 480, 10));
        }// </editor-fold>//GEN-END:initComponents

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel labelNombre;
        private javax.swing.JLabel lableSubtotalTitulo;
        private javax.swing.JLabel labelCantidadTitulo;
        private javax.swing.JLabel labelSubtotal;
        private javax.swing.JLabel labelCantidad;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel panelBorde;
        // End of variables declaration//GEN-END:variables
}
