/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Alici
 */
public class PanelProducto extends javax.swing.JPanel {

    /**
     * Creates new form PanelProducto
     */
    public PanelProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelNombreProducto = new javax.swing.JLabel();
        labelCosto = new javax.swing.JLabel();
        botonSeleccionar = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        panelBorde = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(217, 217, 217));
        setMaximumSize(new java.awt.Dimension(880, 128));
        setMinimumSize(new java.awt.Dimension(880, 128));
        setPreferredSize(new java.awt.Dimension(880, 128));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelNombreProducto.setText("Titulo");
        add(labelNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 470, -1));

        labelCosto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCosto.setText("$ 0.00");
        add(labelCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        botonSeleccionar.setBackground(new java.awt.Color(44, 44, 44));
        botonSeleccionar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        botonSeleccionar.setText("Seleccionar");
        add(botonSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 150, 50));

        jSpinner1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 80, 30));

        panelBorde.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelBordeLayout = new javax.swing.GroupLayout(panelBorde);
        panelBorde.setLayout(panelBordeLayout);
        panelBordeLayout.setHorizontalGroup(
            panelBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        panelBordeLayout.setVerticalGroup(
            panelBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        add(panelBorde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 880, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel labelCosto;
    private javax.swing.JLabel labelNombreProducto;
    private javax.swing.JPanel panelBorde;
    // End of variables declaration//GEN-END:variables
}
