package vista;

import control.ControlComprarProducto;

/**
 * Panel de la interfaz de usuario que muestra un producto individual del
 * catálogo y permite al usuario seleccionar la cantidad deseada.
 *
 * @author Alicia Denise García Acosta 00000252402
 */
public class PanelProducto extends javax.swing.JPanel {

    /**
     * Constructor que inicializa los componentes del panel y configura las
     * opciones del selector de cantidad.
     */
    public PanelProducto() {
        initComponents();
        configurarSpinner();
    }

    /**
     * Configura el modelo del selector de cantidad (JSpinner) para permitir
     * seleccionar valores desde 1 hasta 100.
     */
    private void configurarSpinner() {
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
    }

    /**
     * Establece y muestra el nombre del producto en la etiqueta correspondiente
     * del panel.
     *
     * @param nombre El nombre del producto a mostrar.
     */
    public void setNombreProducto(String nombre) {
        labelNombreProducto.setText(nombre);
    }

    /**
     * Establece y muestra el costo unitario del producto en la etiqueta
     * correspondiente.
     *
     * @param costo El costo del producto a mostrar (generalmente como String
     * formateado).
     */
    public void setCosto(String costo) {
        labelCosto.setText(costo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel1 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                labelNombreProducto = new javax.swing.JLabel();
                labelCosto = new javax.swing.JLabel();
                botonSeleccionar = new javax.swing.JButton();
                jSpinner1 = new javax.swing.JSpinner();
                panelBorde = new javax.swing.JPanel();

                jLabel1.setText("jLabel1");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));

                setBackground(new java.awt.Color(217, 217, 217));
                setMaximumSize(new java.awt.Dimension(880, 128));
                setMinimumSize(new java.awt.Dimension(880, 128));
                setPreferredSize(new java.awt.Dimension(880, 128));
                setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                labelNombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                labelNombreProducto.setText("Titulo");
                add(labelNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 470, -1));

                labelCosto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                labelCosto.setText("$ 0.00");
                add(labelCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

                botonSeleccionar.setBackground(new java.awt.Color(44, 44, 44));
                botonSeleccionar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                botonSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
                botonSeleccionar.setText("Seleccionar");
                botonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                botonSeleccionarActionPerformed(evt);
                        }
                });
                add(botonSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 150, 50));

                jSpinner1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 80, 30));

                panelBorde.setBackground(new java.awt.Color(255, 255, 255));

                javax.swing.GroupLayout panelBordeLayout = new javax.swing.GroupLayout(panelBorde);
                panelBorde.setLayout(panelBordeLayout);
                panelBordeLayout.setHorizontalGroup(
                                panelBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 880, Short.MAX_VALUE));
                panelBordeLayout.setVerticalGroup(
                                panelBordeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 10, Short.MAX_VALUE));

                add(panelBorde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 880, 10));
        }// </editor-fold>//GEN-END:initComponents

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonSeleccionarActionPerformed
        String nombreProducto = labelNombreProducto.getText();
        int cantidad = (Integer) jSpinner1.getValue();
        ControlComprarProducto control = ControlComprarProducto.getInstance();
        control.seleccionarProducto(
                new dtos.ProductoSeleccionadoDTO(nombreProducto, cantidad, 0));
    }// GEN-LAST:event_botonSeleccionarActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton botonSeleccionar;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JSpinner jSpinner1;
        private javax.swing.JLabel labelCosto;
        private javax.swing.JLabel labelNombreProducto;
        private javax.swing.JPanel panelBorde;
        // End of variables declaration//GEN-END:variables
}
