/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.util.ArrayList;
import java.util.List;

import javax.swing.BoxLayout;

/**
 *
 * @author Alici
 */
public class PanelComprarProducto extends javax.swing.JPanel {

    private List<PanelProducto> panelesProducto = new ArrayList<>();
    private List<PanelProductoSeleccionado> panelesProductoSeleccionado = new ArrayList<>();

    /**
     * Creates new form PanelComprarProducto
     */
    public PanelComprarProducto() {
        initComponents();
        contenedorProductosSeleccionados.setLayout(new BoxLayout(contenedorProductosSeleccionados, BoxLayout.Y_AXIS));
        contenedorProductos.setLayout(new BoxLayout(contenedorProductos, BoxLayout.Y_AXIS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLateral = new javax.swing.JPanel();
        labelTituloSeleccionados = new javax.swing.JLabel();
        labelTituloTotal = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        txtNumTarjeta = new javax.swing.JTextField();
        txtRecibo = new javax.swing.JTextArea();
        botonPagar = new javax.swing.JButton();
        labelTituloNumTarjeta = new javax.swing.JLabel();
        scrollPaneProductosSeleccionados = new javax.swing.JScrollPane();
        contenedorProductosSeleccionados = new javax.swing.JPanel();
        labelTituloProductos = new javax.swing.JLabel();
        scrollPaneProductos = new javax.swing.JScrollPane();
        contenedorProductos = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1440, 900));
        setMinimumSize(new java.awt.Dimension(1440, 900));
        setPreferredSize(new java.awt.Dimension(1440, 900));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLateral.setBackground(new java.awt.Color(217, 217, 217));
        panelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTituloSeleccionados.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelTituloSeleccionados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloSeleccionados.setText("Productos seleccionados");
        panelLateral.add(labelTituloSeleccionados, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 23, 444, -1));

        labelTituloTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTituloTotal.setText("Total");
        panelLateral.add(labelTituloTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        labelTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelTotal.setText("$ 0.00");
        panelLateral.add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 410, -1));

        txtNumTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNumTarjeta.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        panelLateral.add(txtNumTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 460, -1));

        txtRecibo.setColumns(20);
        txtRecibo.setRows(5);
        panelLateral.add(txtRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 460, 240));

        botonPagar.setBackground(new java.awt.Color(0, 136, 255));
        botonPagar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        botonPagar.setText("Pagar");
        panelLateral.add(botonPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 830, 500, 70));

        labelTituloNumTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTituloNumTarjeta.setText("Número de tarjeta");
        panelLateral.add(labelTituloNumTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        scrollPaneProductosSeleccionados.setBorder(null);

        contenedorProductosSeleccionados.setBackground(new java.awt.Color(217, 217, 217));
        contenedorProductosSeleccionados.setAutoscrolls(true);
        scrollPaneProductosSeleccionados.setViewportView(contenedorProductosSeleccionados);

        panelLateral.add(scrollPaneProductosSeleccionados,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 500, 400));

        add(panelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 500, 900));

        labelTituloProductos.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        labelTituloProductos.setText("Productos");
        add(labelTituloProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        scrollPaneProductos.setBorder(null);
        scrollPaneProductos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        contenedorProductos.setBackground(new java.awt.Color(255, 255, 255));
        contenedorProductos.setAutoscrolls(true);
        contenedorProductos.setMaximumSize(new java.awt.Dimension(930, 820));
        contenedorProductos.setMinimumSize(new java.awt.Dimension(930, 820));
        scrollPaneProductos.setViewportView(contenedorProductos);

        add(scrollPaneProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 900, 820));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPagar;
    private javax.swing.JPanel contenedorProductos;
    private javax.swing.JPanel contenedorProductosSeleccionados;
    private javax.swing.JLabel labelTituloNumTarjeta;
    private javax.swing.JLabel labelTituloProductos;
    private javax.swing.JLabel labelTituloSeleccionados;
    private javax.swing.JLabel labelTituloTotal;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JScrollPane scrollPaneProductos;
    private javax.swing.JScrollPane scrollPaneProductosSeleccionados;
    private javax.swing.JTextField txtNumTarjeta;
    private javax.swing.JTextArea txtRecibo;
    // End of variables declaration//GEN-END:variables
}
