package vista;

/**
 * Clase que representa el frame principal de la aplicación. Implementa el
 * patrón Singleton para asegurar una única instancia de la ventana principal.
 *
 * @author Alicia Denise García Acosta 00000252402
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Instancia única de la clase (Singleton).
     */
    private static PantallaPrincipal instance;

    /**
     * Constructor privado que inicializa los componentes de la ventana. Se
     * llama solo una vez a través de getInstance().
     */
    private PantallaPrincipal() {
        initComponents();
    }

    /**
     * Método para obtener la instancia única de la clase (Singleton). Si la
     * instancia no existe, la crea.
     *
     * @return La instancia única de PantallaPrincipal.
     */
    public static PantallaPrincipal getInstance() {
        if (instance == null) {
            instance = new PantallaPrincipal();
        }
        return instance;
    }

    /**
     * Actualiza la vista del panel principal de compra. Este método es llamado
     * por el observador del modelo para refrescar la interfaz cuando los datos
     * cambian.
     */
    public void actualizarVista() {
        panelComprarProducto.repaint();
        panelComprarProducto.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelComprarProducto = new vista.PanelComprarProducto();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 900));
        setMinimumSize(new java.awt.Dimension(1440, 900));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelComprarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.PanelComprarProducto panelComprarProducto;
    // End of variables declaration//GEN-END:variables
}
