/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.List;

/**
 *
 * @author Alici
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private static PantallaPrincipal instance;

    /**
     * Creates new form PantallaPrincipal
     */
    private PantallaPrincipal() {
        initComponents();
    }

    public static PantallaPrincipal getInstance() {
        if (instance == null) {
            instance = new PantallaPrincipal();
        }
        return instance;
    }

    public void actualizarVista() {
        panelComprarProducto.repaint();
        panelComprarProducto.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelComprarProducto = new vista.PanelComprarProducto();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1440, 900));
        setMinimumSize(new java.awt.Dimension(1440, 900));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelComprarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.PanelComprarProducto panelComprarProducto;
    // End of variables declaration//GEN-END:variables
}
